#!/bin/sh

# Define el modo de resolución deseado
resolution_mode="1023x658"

# Define la ubicación del archivo de configuración de la resolución de pantalla
config_file="/etc/X11/xorg.conf.d/10-monitor.conf"

# Comprueba si el archivo de configuración existe y borra su contenido si es así
if [ -f "$config_file" ]; then
  > "$config_file"
fi

# Escribe el nuevo contenido en el archivo de configuración
cat <<EOF2 > "$config_file"
Section "Monitor"
  Identifier  "Monitor0"
  Modeline    "$resolution_mode" 83.50 1280 1352 1480 1680 800 803 809 831 -hsync +vsync
  Option      "PreferredMode" "$resolution_mode"
EndSection
EOF2

# Verifica si el modo ya existe en xrandr; si no, créalo
if ! xrandr | grep "$resolution_mode" >/dev/null; then
  echo "Creando nuevo modo de resolución..."
xrandr --newmode "$resolution_mode" 50.00 1023 1072 1168 1312 658 663 673 695 -hsync +vsync
fi

# Imprime un mensaje informativo
echo "Modo de resolución: $resolution_mode"

# Agrega el modo a la salida VGA-1 si aún no está agregado
if ! xrandr -q | grep "$resolution_mode" >/dev/null; then
  xrandr --addmode VGA-1 "$resolution_mode"
fi

# Establece la resolución como predeterminada para la salida VGA-1
xrandr --output VGA-1 --mode "$resolution_mode"

# Reinicia el administrador de ventanas Compton
pkill compton

# Exporta la variable de entorno SESSION_MANAGER
export SESSION_MANAGER=$(dbus-launch)

# Ejecuta xfwm4 con compositor activado en segundo plano
nohup xfwm4 --replace --compositor=on >/dev/null 2>&1 &
